<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LUFTBORN.Contracts\LUFTBORN.Contracts.csproj" />
    <ProjectReference Include="..\LUFTBORN.Domain\LUFTBORN.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Categories\Commands\" />
    <Folder Include="Categories\Events\" />
    <Folder Include="Categories\Queries\" />
  </ItemGroup>

</Project>
