<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\LUFTBORN.Domain\LUFTBORN.Domain.csproj" />
    <ProjectReference Include="..\..\src\LUFTBORN.Application\LUFTBORN.Application.csproj" />
    <ProjectReference Include="..\..\src\LUFTBORN.Infrastructure\LUFTBORN.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

</Project>
